mail:
  mail_username: elearningtechpro@gmail.com
  mail_password: Elearning2022
  mail_from: elearningtechpro@gmail.com
  mail_port: 587
  mail_server: smtp.gmail.com
  mail_tls: True
  mail_ssl: False
  use_credentials: True
  validate_certs: True

project:
  alias: TEL

role:
  user: 0
  admin: 1
  superadmin: 2
